language: python
python: "3.7"
  
install:
  - pip install -U -r requirements.txt
  - pip install --user -r submodules/MPyDATA/requirements.txt
  - pip install --user -e submodules/MPyDATA

script:
  - python -m pytest --ignore submodules --cov-report term --cov=PySDM
  - |
      python -m ipykernel install --user
      for i in examples/*/demo.ipynb; do
         jupyter nbconvert --to markdown --stdout $i > $i.md.repo;
         jupyter nbconvert --ExecutePreprocessor.timeout=1800 --to markdown --execute --stdout $i > $i.md.travis;
         # diff $i.md.repo $i.md.travis  # does not make sense with ipywidgets
      done;
  - |
      for i in examples/*/example.py; do
        PYTHONPATH=. python $i
      done;

after_success:
  - codecov
