language: shell

jobs:
  include:
    - name: "nightly Python build with newest packages on Linux"
      language: python
      python: "nightly"
      before_install:
        - sudo `which pip` install --upgrade pip
      after_install:
        - pip install -U $(pip freeze | cut -d '=' -f 1)
    - name: "Python 3.7 on Linux"
      language: python
      python: 3.7
    - name: "Python 3.7 on OSX"
      os: osx
      before_install:
        - alias python=python3
        - alias pip=pip3
    - name: "Python 3.7 on Windows"
      os: windows
      before_install:
        - choco install python --version 3.7
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip install -U -r requirements.txt
  - pip install -r submodules/MPyDATA/requirements.txt
  - pip install submodules/MPyDATA

script:
  - python -m pytest --ignore submodules --cov-report term --cov=PySDM
  - |
      python -m ipykernel install --user
      for i in PySDM_examples/*/demo.ipynb; do
         jupyter nbconvert --to markdown --stdout $i > $i.md.repo;
         jupyter nbconvert --ExecutePreprocessor.timeout=1800 --to markdown --execute --stdout $i > $i.md.travis;
         # diff $i.md.repo $i.md.travis  # does not make sense with ipywidgets
      done;
  - |
      for i in PySDM_examples/*/example.py; do
        PYTHONPATH=. python $i
      done;

after_success:
  - codecov
