language: shell

jobs:
  include:
    - name: "Python 3.8 build with newest packages on Linux"
      language: python
      python: "3.8"
      before_install:
        - sudo `which pip` install --upgrade pip
      before_script:
        - pip install -U $(pip freeze | cut -d '=' -f 1)
    - name: "Python 3.7 on Linux"
      language: python
      python: 3.7
      after_success:
        - codecov
    - name: "Python 3.7 on OSX"
      os: osx
      before_install:
        - export PY_SFX=3
    - name: "Python 3.7 on Windows"
      os: windows
      before_install:
        - choco install python --version 3.7
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip$PY_SFX install -U -r requirements.txt
  - pip$PY_SFX install -r submodules/MPyDATA/requirements.txt
  - pip$PY_SFX install submodules/MPyDATA

script:
  - python$PY_SFX -m pytest --ignore submodules --cov-report term --cov=PySDM
  - |
      python$PY_SFX -m ipykernel install --user
      for i in PySDM_examples/*/demo.ipynb; do
         jupyter nbconvert --to markdown --stdout $i > $i.md.repo;
         jupyter nbconvert --ExecutePreprocessor.timeout=1800 --to markdown --execute --stdout $i > $i.md.travis;
         # diff $i.md.repo $i.md.travis  # does not make sense with ipywidgets
      done;
  - |
      for i in PySDM_examples/*/example.py; do
        echo $i
        PYTHONPATH=. travis_wait 15 python$PY_SFX $i
      done;
