name: Build Status

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: |
          pip install pytest

      - run: |
          pip install -r requirements.txt
          pip uninstall -y intel-tbb  # TODO (https://github.com/numba/numba/issues/6350#issuecomment-728174860)

      - run: |
          PYTHONPATH=. pytest
